# -*- coding: utf-8 -*-
# ID's
apple_id = XXXXXX
vk_chat_id = X  # shobla = XX, test_apple = XX
tg_chat_id = -XXXXXXXXXXXXX  # -XXXXXXXXX  # zephir = -XXXXXXXXXXXXX, apol_tets = -XXXXXXXXX, apola testit X = -XXXXXXXXX
tg_test_chat_id = -XXXXXXXXXXXXX
tg_requests_chat_id = -XXXXXXXXX

#  Tokens
tmdb_token = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
vk_token = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'  # Telegram Chat
# apl_vk_token = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'  # Андрей Анашкин
tg_token = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'  # Shobla bot
bot_id = 243784053  # Shobla bot
# tg_token = 'XXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'  # Test bot
# bot_id = XXXXXXXXXX  # Test bot
bitly_token = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'